version: '3'

services:
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    ports:
      - "443:443"
    networks:
      - inception
    volumes:
     - wp-volume:/var/www/
    restart: always
# context / dockerfile 안 써도 됨 ?

  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    env_file:
     - .env
    networks:
     - inception
    volumes:
     - db-volume:/var/lib/mysql
    restart: always
  
  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    depends_on:
     - mariadb
    env_file:
     - .env
    networks:
     - inception
    volumes:
     - wp-volume:/var/www/html
    restart: always

volumes:
  db-volume:
    driver: local
    driver_opts:
      device: /home/naki/data/mariadb
      type: none
      o: bind
  wp-volume:
    driver: local
    driver_opts:
      device: /home/naki/data/wordpress
      type: none
      o: bind

networks:
  inception:
    driver: bridge
